trigger:
- master

jobs:
- job: SwiftPM
  pool:
    vmImage: 'macos-latest'
  steps:
  - script: Tests/test_swiftpm.sh
- job: Linux_5_0
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swift:501
  steps:
  - script: Tests/test_swiftpm.sh
- job: Linux_5_1
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swift:51
  steps:
  - script: Tests/test_swiftpm.sh
