#if !canImport(ObjectiveC)
import XCTest

extension AWSS3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSS3Tests = [
        ("testAddObject", testAddObject),
        ("testDeleteObject", testDeleteObject),
        ("testGetObject", testGetObject),
    ]
}

extension AppleAppStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppleAppStoreTests = [
        ("testCoding", testCoding),
        ("testHappyPaht", testHappyPaht),
        ("testOutputErrors", testOutputErrors),
        ("testRedirectToTest", testRedirectToTest),
        ("testVerifyInput", testVerifyInput),
    ]
}

extension FreshDeskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FreshDeskTests = [
        ("testCreateTicket", testCreateTicket),
    ]
}

extension GoogleAnalyticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GoogleAnalyticsTests = [
        ("testCollectAllFields", testCollectAllFields),
        ("testCollectMinimalFields", testCollectMinimalFields),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AWSS3Tests.__allTests__AWSS3Tests),
        testCase(AppleAppStoreTests.__allTests__AppleAppStoreTests),
        testCase(FreshDeskTests.__allTests__FreshDeskTests),
        testCase(GoogleAnalyticsTests.__allTests__GoogleAnalyticsTests),
    ]
}
#endif
